[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
no_match_path = "*/_*"

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config